### ISSUE TITLE
User Experience Review

### ISSUE THREAD

**Issue by rickjohnson** [share-research/pace-admin#44]
- [x] move publication info to right w/ header panel
- [x] highlight current selected person and publication
- [x] year filter should be all years by default with only all applicable years
- [x] remove bulk edit
- [x] add status spinner to top of load publication screen
- [x] remove review counts on top of screen - add undo, redo operations there
- [x] sort person list - alphabetically or by pending count
- [x] review list white space reduced when opening a list to minimum needed - maybe change to tabs instead of one list
- [x] make expanded list of pubs always on bottom
- [x] clearer borders on list
- [x] remove other states if empty lists (maybe always show all as below)
- [x] have filter to show all states or only pending items
- [x] clear middle section until person selected
- [x] on right pane of publication highlight breakdown of confidence metric calculation
- [x] add count tickers above pub list regardless of show all or not
- [x] compact name variation list
- [x] Change hamburger button to dropdown of centers/institute (get rid of drawer)
- [x] Ripple effect
- [x] on right pane of publication highlight breakdown of confidence metric calculation
- [x] highlight common co-authors in co-author list or citation
- [x] in author list if more than x number, then display possible matches plus other relevant co-authors
- [x] collapsible left panelaaa

**Comment by rickjohnson** [comment]
in author list if more than x number, then display possible matches plus other relevant co-authors
remove other states if empty lists (maybe always show all as below)
have filter to show all states or only pending items

**Comment by rickjohnson** [comment]
year filter should be all years by default with only all applicable years
remove review counts on top of screen - add undo, redo operations there
remove bulk edit
Change hamburger button to dropdown of centers/institute (get rid of drawer)

**Comment by rickjohnson** [comment]
add status spinner to top of load publication screen
make expanded list of pubs always on bottom
add count tickers above pub list regardless of show all or not
clearer borders on list 
sort person list - alphabetically by pending count
on right pane of publication highlight breakdown of confidence metric calculation

**Comment by JeffSpies** [comment]
@rickjohnson Hit a few of these, but we still need to improve the look of the dropdown (white background? white arrow?).

**Comment by rickjohnson** [comment]
Updated quite a few items with sorting person, added review status filter, made spacing for review lists compact, and added author list back in because otherwise impossible to tell if a match of just last name for a person

**Comment by rickjohnson** [comment]
added status bar and borders to lists

**Comment by rickjohnson** [comment]
Other possible improvements:

- change to only display one status list at a time when clicking tab buttons
- sort publications by title or confidence

**Comment by rickjohnson** [comment]
Moved "highlight current selected person and publication" to separate issue #69

**Comment by rickjohnson** [comment]
Moved "confidence breakdown" to separate issue #18

**Comment by rickjohnson** [comment]
Moved " highlight common co-authors in co-author list or citation" to separate issue #70

**Comment by rickjohnson** [comment]
Moved "compact name variation list" to separate issue #71
