### ISSUE TITLE
hasura: command not found

### ISSUE THREAD

**Issue by jeremyf** [share-research/pace-admin#76]
I am following the instructions in the README.md. I have Docker Desktop 2.2.0.5 running.

`cp .env.template .env` works

`make cleardb` had the following output:

```console
DOCKER_HOST_IP=host.docker.internal docker-compose down -v
Removing network pace-admin_default
WARNING: Network pace-admin_default not found.
Removing volume pace-admin_postgres_data
WARNING: Volume pace-admin_postgres_data not found.
```

I think that's okay. I then went to `make start_docker`, and it downloaded a lot of things, ending with the following:

```console
Creating pace-admin_redis_1          ... done
Creating pace-admin_graphql-engine_1 ... done
Creating pace-admin_postgres_1       ... done
Creating pace-admin_keycloak_1       ... done
```

I then went to run `make migrate` and go the following (with shell exit status 2):

```console
cd hasura && hasura migrate apply && cd ..
/bin/sh: hasura: command not found
make: *** [migrate] Error 127
```

**Comment by rickjohnson** [comment]
Yeah the make migrate thing is is a known quirk, where there are few things that need to start up before it will run.  Maybe there is a more graceful way to handle this?  

For the cleardb you are prob OK.
